graph TD
    subgraph MASTER_S_DEGREE
    ADULT_PATIENTS[ADULT_PATIENTS]
    FIRST_ICU_STAYS[FIRST_ICU_STAYS]
    ICU_STAYS_MIN_DURATION[ICU_STAYS_MIN_DURATION]
    SEPSIS_3_PATIENTS[SEPSIS_3_PATIENTS]
    SEPSIS_3_PATIENTS_EXCLUDED_PREEXISTING[SEPSIS_3_PATIENTS_EXCLUDED_PREEXISTING]
    TMP_VASOPRESSOR_USE[TMP_VASOPRESSOR_USE]
    TMP_HYPOTENSION[TMP_HYPOTENSION]
    TMP_HIGH_LACTATE[TMP_HIGH_LACTATE]
    SEPSIS_AND_SHOCK_PATIENTS[SEPSIS_AND_SHOCK_PATIENTS]
    ALL_ADULT_ICU_PATIENTS[ALL_ADULT_ICU_PATIENTS]
    tmp_vital_signs[tmp_vital_signs]
    tmp_sofa_score[tmp_sofa_score]
    HOURLY_VITAL_SIGNS[HOURLY_VITAL_SIGNS]
    HOURLY_VITAL_SIGNS_NEW_SEPSIS[HOURLY_VITAL_SIGNS_NEW_SEPSIS]
    VITAL_SIGNS_6H_WINDOW[VITAL_SIGNS_6H_WINDOW]
    HOURLY_VITAL_SIGNS_FILTERED[HOURLY_VITAL_SIGNS_FILTERED]
    HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS[HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS]
    end
    subgraph master_s_degree
    filtered_hourly_vital_signs[filtered_hourly_vital_signs]
    avg_hourly_vital_signs[avg_hourly_vital_signs]
    end
    SEPSIS_3_PATIENTS --> SEPSIS_3_PATIENTS_EXCLUDED_PREEXISTING
    SEPSIS_3_PATIENTS_EXCLUDED_PREEXISTING --> SEPSIS_3_PATIENTS
    HOURLY_VITAL_SIGNS --> HOURLY_VITAL_SIGNS_FILTERED
    HOURLY_VITAL_SIGNS --> HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS
    HOURLY_VITAL_SIGNS_FILTERED --> HOURLY_VITAL_SIGNS
    HOURLY_VITAL_SIGNS_FILTERED --> HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS
    HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS --> HOURLY_VITAL_SIGNS_FILTERED
    HOURLY_VITAL_SIGNS_FILTERED_WITH_TRENDS --> HOURLY_VITAL_SIGNS
